.golangci.yml, config/app.go, internal/entities/info/server.go, internal/entities/sensor/mqtt.go, internal/mapper/basic_types_mapper.go, internal/mapper/info.go, internal/server/http/middleware.go, internal/server/http/server.go, internal/server/mqtt/mqtt.go, internal/service/domain/info/app.go, internal/service/domain/info/app_test.go, internal/service/domain/sensor/mqtt.go, internal/service/domain/service.go, internal/service/domain/tree/tree.go, internal/service/entities/info/app.go, internal/service/entities/sensor/mqtt.go, internal/service/entities/tree/prediction.go, internal/service/entities/tree/reponse.go, internal/service/entities/tree/tree.go, internal/service/service.go, internal/storage/entities/info/server.go, internal/storage/entities/sensor/sensor.go, internal/storage/local/info/app.go, internal/storage/mongodb/storage.go, internal/storage/storage.go, main.go
This PR fixes the linter annotations
=> chore: fix linter annotation

config/app.go, internal/logger/logger.go, internal/server/http/handler/error_handler.go, internal/server/http/middleware.go, internal/server/http/middleware/health_check.go, internal/server/http/middleware/logger.go, internal/server/http/server.go, internal/server/mqtt/mqtt.go, internal/service/domain/sensor/mqtt.go, internal/service/domain/tree/tree.go, internal/service/service.go, internal/storage/mongodb/sensor/mqtt.go, internal/storage/mongodb/storage.go, main.go
=> feat: implement logger

internal/server/http/entities/tree/tree.go, internal/server/http/handler/v1/tree/handler.go, internal/server/http/handler/v1/tree/routes.go, internal/server/http/router.go
Close #42 
Provide endpoints for retrieving, creating, updating and deleting trees, and for creating and removing images and sensors for a tree
=> feat: implement tree api

internal/server/http/entities/treecluster/treecluster.go, internal/server/http/handler/v1/treecluster/handler.go, internal/server/http/handler/v1/treecluster/routes.go, internal/server/http/router.go
Close #31 
Provide endpoints for retrieving, creating, updating and deleting tree clusters, and for creating and removing trees from a tree cluster.
=> feat: implement treeclusert api

internal/entities/auth.go, internal/server/http/handler/v1/user/handler.go, internal/service/domain/auth/user.go, internal/service/service.go
=> fix: wrong swagger definition

.golangci.yml, internal/server/http/entities/mapper/region.go, internal/server/http/entities/mapper/sensor.go, internal/server/http/entities/mapper/tree.go, internal/server/http/entities/mapper/treecluster.go, internal/server/http/entities/region.go, internal/server/http/entities/treecluster.go, internal/server/http/handler/v1/region/handler.go, internal/server/http/handler/v1/tree/handler.go, internal/service/domain/tree/tree.go, internal/service/service.go, internal/utils/basic_types_mapper.go
=> feat: add tree logic to get trees

internal/entities/treecluster.go, internal/server/http/entities/treecluster.go, internal/service/domain/treecluster/treecluster.go, internal/storage/postgres/treecluster/get.go, internal/storage/postgres/treecluster/update.go, internal/storage/storage.go
=> feat: remove not needed fields in update tree cluster and change update logic

.mockery.yaml, internal/server/http/entities/tree.go, internal/server/http/handler/v1/sensor/handler.go, internal/server/http/handler/v1/sensor/routes.go, internal/server/http/router.go, internal/service/domain/sensor/sensor.go, internal/service/domain/service.go, internal/service/service.go, internal/service/service_test.go
Work with green-ecolution/green-ecolution-frontend#126
=> feat: change service and entities for create and update trees and get sensor

internal/entities/tree.go, internal/service/domain/service.go, internal/service/domain/tree/tree.go, internal/service/domain/treecluster/geo_locator.go, internal/service/domain/treecluster/treecluster.go
=> feat: add component geo locator to handler cluster calculation

CHANGELOG.md
=> docs: Added changelog

internal/server/http/entities/auth.go, internal/server/http/handler/v1/fileimport/handler.go, internal/server/http/handler/v1/info/handler.go, internal/server/http/handler/v1/region/handler.go, internal/server/http/handler/v1/role/handler.go, internal/server/http/handler/v1/sensor/handler.go, internal/server/http/handler/v1/tree/handler.go, internal/server/http/handler/v1/treecluster/handler.go, internal/server/http/handler/v1/user/handler.go, internal/server/http/middleware/jwt.go, internal/server/http/router.go, internal/service/domain/auth/token.go, internal/service/service.go, internal/storage/auth/keycloak/token.go, internal/storage/storage.go, main.go
ref green-ecolution/green-ecolution-frontend#175
=> Handle refresh token

internal/entities/tree.go, internal/service/domain/tree/tree.go, internal/storage/postgres/queries/trees.sql, internal/storage/postgres/store/store.go, internal/storage/postgres/tree/create.go, internal/storage/postgres/tree/update.go
Close #122 
Close #124 
Close #125 
Close #126 
Close #127
=> bugfix: fix create tree logic

internal/server/http/handler/v1/user/handler.go
ref green-ecolution/green-ecolution-frontend#186
=> feat: return 401 if token can not be refreshed

internal/server/http/entities/sensor.go
=> feat: remove omitempty in sensor list reponse

internal/server/http/handler/v1/sensor/handler.go, internal/server/http/handler/v1/sensor/handler_test.go, internal/server/http/handler/v1/sensor/routes.go, internal/server/http/handler/v1/sensor/routes_test.go, internal/server/http/handler/v1/sensor/utils.go, internal/utils/utils.go
=> feat: add handler tests for sensor

internal/service/domain/auth/user_test.go
=> feat: add test cases for logout request

internal/utils/basic_types_mapper.go, internal/utils/basic_types_mapper_test.go, internal/utils/iterators_test.go, internal/utils/slices_test.go, internal/utils/sqlc_mapper_test.go, internal/utils/utils.go, internal/utils/utils_test.go
=> test: utilities

internal/entities/treecluster.go, internal/service/domain/treecluster/treecluster.go, internal/service/domain/treecluster/treecluster_test.go, internal/storage/auth/keycloak/token_test.go
=> feat: add treecluster struct validation in service

config.enc.yaml, config/app.go, config/auth.go, internal/server/http/handler/v1/user/handler.go, internal/server/http/handler/v1/user/handler_test.go, internal/server/http/handler/v1/user/routes_test.go, internal/server/http/middleware/jwt.go, internal/service/domain/auth/user.go, internal/service/domain/auth/user_test.go, internal/storage/auth/keycloak/testutils/suite.go, internal/storage/auth/keycloak/testutils/utils.go, internal/storage/auth/keycloak/token.go, internal/storage/auth/keycloak/token_test.go, internal/storage/auth/keycloak/user.go
Close #170 
> [!WARNING]
> I have changed the layout of the config file in this PR. When the PR is merged, the config needs to be updated in each local dev setup as well as in the deployments.
=> test: server user tests

.mockery.yaml, internal/service/domain/service.go, internal/service/domain/tree/tree.go, internal/service/domain/tree/tree_test.go, internal/service/domain/treecluster/geo_locator.go, internal/service/domain/treecluster/geo_locator_test.go, internal/service/domain/treecluster/treecluster.go, internal/service/domain/treecluster/treecluster_test.go, internal/service/service.go, internal/storage/postgres/storage.go, internal/storage/postgres/store/store.go, internal/storage/postgres/store/store_test.go, internal/storage/postgres/testutils/suite.go, internal/storage/postgres/treecluster/create.go, internal/storage/postgres/treecluster/create_test.go, internal/storage/postgres/treecluster/treecluster_test.go, internal/storage/postgres/treecluster/update.go, internal/storage/postgres/treecluster/update_test.go, internal/storage/storage.go
Ref #85 
my suggestion for the implementation of transactions. In this PR only transactions for treecluster were implemented
- refactor treecluster repo and service
- refactor geo locator
- implement transaction
- change store implementation
- add unit test for store
=> feat: implement transaction for tree cluster

internal/service/domain/tree/tree_test.go
Dont know why exactly but there was an issue on merge #235 into develop
=> hotfix: to many arguments

.github/workflows/test-migrations-on-pr.yaml, internal/storage/postgres/seed/99_demo_data.sql
Fix migration (seed down) and add workflow to test migrations and seed
=> Fix migrations

internal/storage/postgres/tree/get_test.go
=> feat: add repo test for get tree by sensor id

internal/storage/postgres/mapper/watering_plan_test.go
=> feat: add test for watering plan mapper

internal/server/http/entities/plugin.go, pkg/plugin/http_func.go, pkg/plugin/plugin.go, pkg/plugin/types.go, pkg/plugin/worker.go
Close #249 
Based on #196 wich need to merge first
=> feat: plugin libary

internal/server/mqtt/mqtt.go, internal/service/domain/sensor/mqtt.go, internal/service/domain/sensor/mqtt_test.go, internal/service/domain/sensor/sensor.go, internal/service/domain/service.go, internal/service/domain/service_test.go, internal/service/service.go, internal/service/service_test.go
=> feat: merge mqtt service with sensor service

.envrc, .gitignore, Makefile, flake.lock, flake.nix
=> feat: improve dev setup

.docker/docker-compose.infra.yaml, .docker/infra/pgadmin/servers.json
Stop prompting for a password now and autoconfigure the local db server when starting
**NOTE:**
- `make infra/up`
- `make infra/stop`
- `make infra/down`
=> infra: change local pgadmin

internal/entities/events.go, internal/service/domain/sensor/mqtt.go, internal/service/domain/sensor/mqtt_test.go, internal/service/domain/sensor/sensor.go, internal/service/domain/sensor/sensor_test.go, internal/service/domain/service.go, internal/service/domain/tree/tree.go, internal/service/domain/treecluster/handle_new_sensor_data.go, internal/service/domain/treecluster/handle_new_sensor_data_test.go, internal/service/domain/treecluster/handle_tree_update.go, internal/service/domain/treecluster/handle_tree_update_test.go, internal/service/domain/utils/watering_status.go, internal/service/domain/utils/watering_status_test.go, internal/service/service.go, internal/storage/postgres/mapper/sensor.go, internal/storage/postgres/queries/treecluster.sql, internal/storage/postgres/queries/trees.sql, internal/storage/postgres/seed/test/treecluster/02_treecluster.sql, internal/storage/postgres/store/utils.go, internal/storage/postgres/tree/get.go, internal/storage/postgres/tree/get_test.go, internal/storage/postgres/treecluster/get.go, internal/storage/postgres/treecluster/get_test.go, internal/storage/storage.go, internal/worker/subscriber/subscriber.go, main.go
=> feat: update watering status on new data

internal/storage/postgres/treecluster/treecluster.go, internal/storage/postgres/vehicle/vehicle.go
=> chore: delete not needed functions

internal/entities/vehicle.go, internal/server/http/entities/vehicle.go, internal/service/domain/vehicle/vehicle.go, internal/service/domain/vehicle/vehicle_test.go, internal/storage/postgres/migrations/20250107161147_vehicle_add_weight.sql, internal/storage/postgres/queries/vehicles.sql, internal/storage/postgres/seed/99_demo_data.sql, internal/storage/postgres/seed/test/vehicle/01_vehicle.sql, internal/storage/postgres/vehicle/create.go, internal/storage/postgres/vehicle/create_test.go, internal/storage/postgres/vehicle/get_test.go, internal/storage/postgres/vehicle/update.go, internal/storage/postgres/vehicle/update_test.go
=> feat: add attribute weight for vehicle

internal/service/domain/tree/tree.go, internal/service/domain/treecluster/handle_tree_update.go, internal/service/domain/treecluster/handle_tree_update_test.go, internal/service/service.go, internal/worker/subscriber/subscriber.go, internal/worker/subscriber/subscriber_test.go
=> bugfix: tree events

internal/service/domain/treecluster/handle_new_sensor_data.go
=> fix: change logs and check if sensor or tree not found

internal/server/http/server.go, internal/service/service.go
=> feat: run sensor status schedular

internal/service/domain/treecluster/handle_new_sensor_data.go, internal/service/domain/treecluster/handle_new_sensor_data_test.go
=> bugfix: handle error on no linked tree cluster

internal/entities/routing.go, internal/server/http/entities/routing.go, internal/server/http/handler/v1/watering_plan/handler.go, internal/storage/routing/convert_locations.go, internal/storage/routing/openrouteservice/repo.go, internal/storage/routing/valhalla/repo.go
=> feat: add metadata of start point, end point and refill point

.docker/docker-compose.infra.yaml, internal/service/domain/treecluster/treecluster.go, internal/service/domain/treecluster/treecluster_test.go
Close #339 
Close #336 
I am not sure if this is a nice way to fix this error. Please check if there are other possibilities and if this is clean enough …
=> fix: tree cluster update on empty trees

internal/entities/routing.go, internal/entities/watering_plan.go, internal/server/http/entities/mapper/watering_plan.go, internal/server/http/entities/watering_plan.go, internal/service/domain/watering_plan/watering_plan.go, internal/storage/postgres/mapper/watering_plan.go, internal/storage/postgres/migrations/20250112120233_watering_plan_add_duration_and_refills.sql, internal/storage/postgres/queries/watering_plans.sql, internal/storage/postgres/watering_plan/create.go, internal/storage/postgres/watering_plan/update.go, internal/storage/routing/openrouteservice/ors/entities.go, internal/storage/routing/openrouteservice/ors/ors.go, internal/storage/routing/openrouteservice/repo.go, internal/storage/routing/valhalla/repo.go, internal/storage/routing/valhalla/valhalla/valhalla.go, internal/storage/routing/vroom/utils.go, internal/storage/storage.go, internal/utils/basic_types_mapper.go
Return information about the generated route, such as distance, time and refills
=> feat: return route metadata on generating route

internal/service/domain/sensor/mqtt.go, internal/service/domain/sensor/sensor.go, internal/service/domain/tree/tree.go, internal/service/domain/treecluster/handle_tree_update_test.go, internal/service/domain/treecluster/handle_watering_plan_update.go, internal/service/domain/treecluster/treecluster.go, internal/service/domain/watering_plan/watering_plan.go, internal/worker/manager.go, internal/worker/manager_test.go
=> feat: increase event buffer size

internal/server/http/handler/v1/plugin/handler.go, internal/server/http/handler/v1/plugin/routes.go, internal/service/domain/plugin/manager.go, internal/service/service.go, pkg/client/README.md, pkg/client/api/openapi.yaml, pkg/client/api_plugin.go, pkg/client/api_sensor.go, pkg/client/api_vehicle.go, pkg/client/api_watering_plan.go, pkg/client/test/api_plugin_test.go, pkg/plugin/go.mod, pkg/plugin/http_func.go, pkg/plugin/types.go, pkg/plugin/worker.go
=> feat: add plugin refresh token

internal/server/http/entities/region.go, internal/server/http/entities/sensor.go, internal/server/http/entities/tree.go, internal/server/http/entities/treecluster.go, internal/server/http/entities/user.go, internal/server/http/entities/vehicle.go, internal/server/http/entities/watering_plan.go, internal/server/http/handler/v1/region/handler.go, internal/server/http/handler/v1/user/handler.go, internal/utils/pagination/pagination.go, internal/utils/pagination/pagination_test.go, pkg/client/api/openapi.yaml, pkg/client/model_region_list.go, pkg/client/model_sensor_list.go, pkg/client/model_tree_cluster_list.go, pkg/client/model_tree_list.go, pkg/client/model_user_list.go, pkg/client/model_vehicle_list.go, pkg/client/model_watering_plan_list.go
- Pagination can be null, so I added `omitempty` and `validate:"optional"` so that Swagger can handle it
- if there are no values set for `limit` and `page` in the context, default values are returned instead of error
=> feat: change pagination definition in swagger

internal/service/domain/treecluster/treecluster.go
=> fix: check if region is not nil before accessing it

config/config.dev.enc.yaml, config/config.prod.enc.yaml, config/config.stage.enc.yaml
=> chore: adjust logger format config

.docker/config.default.yaml, config/config.dev.enc.yaml, config/config.prod.enc.yaml, config/config.stage.enc.yaml, internal/server/mqtt/mqtt.go, internal/service/domain/tree/handle_new_sensor_data.go, internal/storage/postgres/sensor/create.go
=> fix: adjust TTN attribute names

internal/service/domain/watering_plan/watering_plan.go, internal/storage/routing/vroom/vroom.go
=> fix: set default water capacity to 80 liters

internal/service/domain/treecluster/treecluster.go
=> fix: add region if not set

internal/config/app.go, internal/config/viper.go, internal/server/http/handler/v1/user/handler.go, internal/server/http/handler/v1/user/routes.go, internal/server/http/middleware/jwt.go, internal/server/http/middleware/jwt_test.go, internal/service/domain/auth/dummy.go, internal/service/domain/plugin/dummy.go, internal/service/domain/service.go, internal/service/domain/watering_plan/watering_plan.go, internal/service/service.go, internal/storage/auth/dummy.go, internal/storage/auth/storage.go, internal/storage/postgres/treecluster/get_test.go, internal/storage/routing/dummy.go, internal/storage/s3/dummy.go, internal/storage/storage.go, main.go
add ability to:
- disable auth
- disable routing services
- disable s3
- disable mqtt
=> feat: implement demo

internal/entities/tree.go, internal/server/http/handler/v1/evaluation/handler.go, internal/server/http/handler/v1/tree/handler.go, internal/server/http/handler/v1/tree/handler_test.go, internal/server/http/handler/v1/tree/routes_test.go, internal/server/http/handler/v1/tree/utils_test.go, internal/service/domain/evaluation/evaluation.go, internal/service/domain/evaluation/evaluation_test.go, internal/service/domain/tree/tree.go, internal/service/domain/tree/tree_test.go, internal/service/domain/tree/utils_test.go, internal/service/service.go, internal/storage/postgres/queries/trees.sql, internal/storage/postgres/tree/get.go, internal/storage/postgres/tree/get_test.go, internal/storage/postgres/treecluster/create_test.go, internal/storage/postgres/treecluster/update_test.go, internal/storage/storage.go
=> feat: add filter to tree

internal/service/domain/treecluster/treecluster.go
=> fix: update watering status of old tree cluster

internal/storage/postgres/seed/99_demo_data.sql
=> fix: set watering status to unkown at trees without sensor

internal/service/domain/sensor/mqtt.go, internal/service/domain/sensor/mqtt_test.go, internal/service/domain/sensor/sensor.go
=> feat: map sensor to tree when it sends data from ttn

internal/service/domain/watering_plan/watering_plan.go
=> fix: only one user needs required driving licences

internal/storage/postgres/seed/99_demo_data.sql
=> fix: Creating tree sometimes does not work: unique constraint
